# Generated by Django 6.0.7 on 2026-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField()),
                ('pdf', models.URLField(blank=True)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('rating', models.FloatField()),
                ('about_author', models.TextField()),
                ('preview', models.TextField()),
            ],
        ),
    ]
