# Generated by Django 6.0.7 on 2026-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_about_author_book_aboutauthor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='preview',
        ),
        migrations.AddField(
            model_name='book',
            name='downloadLink',
            field=models.URLField(default='https://www.gutenberg.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='viewLink',
            field=models.URLField(default='https://www.gutenberg.org'),
            preserve_default=False,
        ),
    ]
