# Generated by Django 6.0.7 on 2026-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_pdf_remove_book_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.TextField(default='View the full book using the View Full Book button.'),
            preserve_default=False,
        ),
    ]
