# Generated by Django 6.0.7 on 2026-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='downloadLink',
            field=models.CharField(max_length=300),
        ),
    ]
